DELETE  http://vm4.sese.tu-berlin.de:3001/api/room
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjA2MWVmZjdkZTg4N2MxMmUwMTU2Iiwicm9vbSI6Mywicm9sZSI6IkFkbWluIiwiaWF0IjoxNjEyNzkyNjYyLCJleHAiOjE2MTI3OTQ0NjJ9.K7TV3_QgHQdsl9q9FsfBcF50Ar5Tx9whJ6glzVcebfI '

{
  "roomID" : "4",
  "password" : "12"
}
###
POST http://vm4.sese.tu-berlin.de:3001/api/create-room/
Content-Type: application/json

{
  "password" : "12"
}
###
POST  http://localhost:3000/api/login
Content-Type: application/json

{
  "roomID" : "1",
  "password" : "12"
}

###
GET  https://vm4.sese.tu-berlin.de:3000/api/room/2/admin
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjQzMjhhMTdjNTFlYzA2YmM0OGI5Iiwicm9vbSI6Miwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjEyNzg5MTIyLCJleHAiOjE2MTI3OTA5MjJ9.S9-kOYNtpJBQjLou0tIPBQ8r8Gf3nwVwkFjgHCkz_cs '

{
  "soundtracks": [{"userID" : "1", "instrument" : "retinstrument123", "soundSequence":[{"starttime" : "4", "endtime": "12", "pitch":"23"}]}]
}

###
DELETE  http://localhost:3000/api/room/3/admin
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjdjMTI2NTIxZjJkNDBhZTZhZWRkIiwicm9vbSI6Mywicm9sZSI6IkFkbWluIiwiaWF0IjoxNjExNzU0NjQwLCJleHAiOjE2MTE3NTY0NDB9.4bTsEWwYdTFohCZp7SpwO04LI6TmuhtcUb_ZbVqg0LE '

{
  "roomID": "3"
}
###
POST   http://localhost:3000/api/room/1/
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjQ5NTc3MzBjYjAxOGM3NDg5N2RlIiwicm9vbSI6Miwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjEwMzY0NDk1LCJleHAiOjE2MTAzNjYyOTV9.jmnocng_X6icxN7yy78sFe2fVkDus9kuGZbOIwhBp-U '

{
  "soundtracks": [{"userID" : 1, "instrument" : "retinstrument123", "number" : 1, "soundSequence":[{"starttime" : "4", "endtime": "12", "pitch":"23"}]}]
}
###
DELETE   http://localhost:3000/api/room/1
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjQ5NTc3MzBjYjAxOGM3NDg5N2RlIiwicm9vbSI6Miwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjEwMzY0NDk1LCJleHAiOjE2MTAzNjYyOTV9.jmnocng_X6icxN7yy78sFe2fVkDus9kuGZbOIwhBp-U '

{
  "roomID" : 1,
  "userID" : 1,
  "instrument" : "retinstrument123",
  "number" : 1
}
###
POST http://localhost:3000/api/room/1/beat
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6ImJhYmViN2E0NjEwNWE1MWUzM2UzIiwicm9vbSI6IjEiLCJyb2xlIjoiVXNlciIsImlhdCI6MTYxMjAwNjI1OSwiZXhwIjoxNjEyMDA4MDU5fQ.4D_Gar3dM4GmUs3MW6sHdOlpWDxJ-BV5uFhiyP12OgQ '

{
  "roomID" : 1,
  "beat" : {"ticksPerTact" : 321, "tempo": 21}, 
  "userID" : 1,
  "instrument" : "instrument123",
  "number" : 1
}