DELETE  http://localhost:3000/api/room
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjFiZDIxNWI4MjIwODRiNjJhNDdjIiwicm9vbSI6IjQiLCJyb2xlIjoiQWRtaW4iLCJpYXQiOjE2MDg3MTQxMjgsImV4cCI6MTYwODcxNTkyOH0.fUUQKGF_l6dtFn0dROE1-iaQ7UjlDPsuoFqXJbU3fPI '

{
  "roomID" : "4",
  "password" : "12"
}
###
POST http://localhost:3000/api/create-room
Content-Type: application/json

{
  "password" : "12"
}
###
POST  http://localhost:3000/api/login
Content-Type: application/json

{
  "roomID" : "1",
  "password" : "12"
}