DELETE  http://localhost:3000/api/room
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6Ijg0MmI1MzViYTMyOWExYzhiYjllIiwicm9vbSI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjA5NzEyMTY4LCJleHAiOjE2MDk3MTM5Njh9.GsdfRxw2oDCfLke1fj4O5xzlFHcF83eVnZ_LoSs5AEw '

{
  "roomID" : "1",
  "password" : "12"
}
###
POST http://localhost:3000/api/create-room
Content-Type: application/json

{
  "password" : "12"
}
###
POST  http://localhost:3000/api/login
Content-Type: application/json

{
  "roomID" : "1",
  "password" : "12"
}

###
GET  http://localhost:3000/api/room/1/
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjQ5NTc3MzBjYjAxOGM3NDg5N2RlIiwicm9vbSI6Miwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjEwMzY0NDk1LCJleHAiOjE2MTAzNjYyOTV9.jmnocng_X6icxN7yy78sFe2fVkDus9kuGZbOIwhBp-U '

{
  "soundtracks": [{"userID" : "1", "instrument" : "retinstrument123", "soundSequence":[{"starttime" : "4", "endtime": "12", "pitch":"23"}]}]
}

###
DELETE  http://localhost:3000/api/room/1/admin
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6ImNhZjRmYWI4NzgwYjhlZTRmMGI3Iiwicm9vbSI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjEwMzE0Nzk3LCJleHAiOjE2MTAzMTY1OTd9.npXUKR4yDVhSDdoqYhNPsBD_K51I-qIj7bNgKkCz1R8 '

{
  "roomID": "1"
}
###
POST   http://localhost:3000/api/room/1/
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjQ5NTc3MzBjYjAxOGM3NDg5N2RlIiwicm9vbSI6Miwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjEwMzY0NDk1LCJleHAiOjE2MTAzNjYyOTV9.jmnocng_X6icxN7yy78sFe2fVkDus9kuGZbOIwhBp-U '

{
  "soundtracks": [{"userID" : 1, "instrument" : "retinstrument123", "number" : 1, "soundSequence":[{"starttime" : "4", "endtime": "12", "pitch":"23"}]}]
}
###
DELETE   http://localhost:3000/api/room/1
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjQ5NTc3MzBjYjAxOGM3NDg5N2RlIiwicm9vbSI6Miwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjEwMzY0NDk1LCJleHAiOjE2MTAzNjYyOTV9.jmnocng_X6icxN7yy78sFe2fVkDus9kuGZbOIwhBp-U '

{
  "roomID" : 1,
  "userID" : 1,
  "instrument" : "retinstrument123",
  "number" : 1
}
###
GET http://localhost:3000/api/room/1/admin
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6Ijk4ZDBjMWE0ZDc1MzgwZGNjZWMzIiwicm9vbSI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjEwMzE0NTIyLCJleHAiOjE2MTAzMTYzMjJ9.KRu4fEY9yBmJd9Jv2VAVrTb6PSK7Qmew52C5PZn-XxA '

{
  "roomID" : 1,
  "userID" : 1,
  "instrument" : "instrument123",
  "number" : 1
}