DELETE  http://localhost:3000/api/room
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjMyMTI0NzAyNzVjOWY2NmM1ZTBlIiwicm9vbSI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjA5MDUzMDI1LCJleHAiOjE2MDkwNTQ4MjV9.bqe8_OZnAXKT6ujr9fBz8xNLLgJ518GOn6XLhQSr7yA '

{
  "roomID" : "1",
  "password" : "12"
}
###
POST http://localhost:3000/api/create-room
Content-Type: application/json

{
  "password" : "12"
}
###
POST  http://localhost:3000/api/login
Content-Type: application/json

{
  "roomID" : "1",
  "password" : "12"
}

###
POST  http://localhost:3000/api/room/1
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJybmRtUGF5bG9hZCI6IjY1MjVkM2FiMWM2NzA1N2ViZmIxIiwicm9vbSI6MSwicm9sZSI6IkFkbWluIiwiaWF0IjoxNjA5NjcxODIxLCJleHAiOjE2MDk2NzM2MjF9.QAVyGnXg5x50hxq5O9tboWf0azwMFum5CUqiawqdOxE '

{
  "roomID" : "1",
  "userID" : "2", 
  "instrument" : "guitar",
  "starttime" : "2",
  "pitch" : "1"
}
###